server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: car-tech-tracker-backend
  
  # CORS configuration for frontend
  web:
    cors:
      allowed-origins: 
        - "http://localhost:3000"
        - "http://127.0.0.1:3000"
        - "file://"
      allowed-methods: 
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers: 
        - "*"
      allow-credentials: true

# JWT Configuration
jwt:
  secret: "your-secret-key-change-in-production"
  expiration: 86400000 # 24 hours in milliseconds

# Logging
logging:
  level:
    com.cartech: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Demo mode configuration
demo:
  enabled: true
  default-user:
    email: "demo@example.com"
    password: "demo123"
    name: "Demo User" 